import uuid
from datetime import datetime
from sqlmodel import select, Session
from models.table_sessions import TableSession
from models.order_items import OrderItem
from models.table_participants import TableParticipant
from schemas.table_sessions import SessionCreate, SessionClose


def create_session_with_items(
    db: Session,
    session_data: SessionCreate
) -> TableSession:
    """
    Create a new table session with order items.
    Session id is generated by hashing the restaurant_id, table_id and session_start timestamp.
    """
    session_id = uuid.uuid5(uuid.NAMESPACE_URL, f"{session_data.restaurant_id}-{session_data.table_id}-{session_data.session_start.isoformat()}")
    session = TableSession(
        id=session_id,
        restaurant_id=session_data.restaurant_id,
        table_id=session_data.table_id,
        session_start=session_data.session_start,
    )
    db.add(session)
    db.flush()  # Flush to get the session.id
    
    for item in session_data.items:
        order_item = OrderItem(
            session_id=session.id,
            item_name=item.item_name,
            unit_price=item.unit_price,
        )
        db.add(order_item)
    
    db.commit()
    db.refresh(session)
    return session


def get_session_by_id(
    db: Session,
    session_id: uuid.UUID
) -> TableSession | None:
    """Get a session by its ID."""
    return db.get(TableSession, session_id)


def get_session_items(
    db: Session,
    session_id: uuid.UUID
) -> list[OrderItem]:
    """Get all order items for a session."""
    items = db.exec(
        select(OrderItem).where(OrderItem.session_id == session_id)
    ).all()
    return items


def get_session_participants(
    db: Session,
    session_id: uuid.UUID
) -> list[TableParticipant]:
    """Get all participants for a session."""
    participants = db.exec(
        select(TableParticipant).where(TableParticipant.session_id == session_id)
    ).all()
    return participants


def close_session(
    db: Session,
    session_id: uuid.UUID,
    close_data: SessionClose
) -> TableSession:
    """Close a session by updating its status and session_end."""
    session = db.get(TableSession, session_id)
    if not session:
        raise ValueError("Session not found")
    
    session.status = close_data.status
    session.session_end = datetime.now()
    
    db.add(session)
    db.commit()
    db.refresh(session)
    
    return session

