"""empty message

Revision ID: e709f18c45e6
Revises: 05f08a87555b
Create Date: 2025-11-08 11:00:57.266094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e709f18c45e6'
down_revision: Union[str, Sequence[str], None] = '05f08a87555b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('from_user', sa.Uuid(), nullable=False),
    sa.Column('to_user', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payments')
    op.add_column('invoices', sa.Column('settlement_id', sa.Uuid(), nullable=True))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'settlements', ['settlement_id'], ['id'])
    op.drop_column('invoices', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('payment_id', sa.CHAR(length=32), nullable=True))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'payments', ['payment_id'], ['id'])
    op.drop_column('invoices', 'settlement_id')
    op.create_table('payments',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('invoice_id', sa.CHAR(length=32), nullable=True),
    sa.Column('from_user', sa.CHAR(length=32), nullable=False),
    sa.Column('to_user', sa.CHAR(length=32), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('settlement_date', sa.DATE(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('settlements')
    # ### end Alembic commands ###
